server:
  port: 8050
spring:
  application:
    name: batch-processor-lab
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml