spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
  liquibase:
    url: jdbc:postgresql://localhost:5432/db
    user: root
    password: root